# -*- coding: utf-8 -*-
"""task1-.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WahdREIcsuED30xbMG2pLtgvpeW1s9rm
"""

from google.colab import drive
drive.mount('/content/drive')

import json
import pandas as pd

# Read the CSV file
csv_path = '/content/drive/MyDrive/to_fill.csv'
df = pd.read_csv(csv_path)

# Define a function to extract the body, start time, and end time from a JSON file
def extract_info(json_path):
    with open(json_path, 'r') as f:
        json_data = json.load(f)
    
    body = json_data['text']  # replace 'full_text' with 'text'
    start = json_data['words'][0]['start']
    end = json_data['words'][-1]['end']
    
    return body, start, end


# Define a function to extract the first 8 and last 8 words from a story
def extract_first_last_words(row):
    words = row['body'].split()
    first_words = ' '.join(words[:8])
    last_words = ' '.join(words[-8:])
    return first_words, last_words



# Iterate over the JSON file paths and add the required columns to the dataframe
json_paths = ['/content/drive/MyDrive/18246.json',
              '/content/drive/MyDrive/16859.json',
              '/content/drive/MyDrive/12387.json']

for json_path in json_paths:
    transcription_id = json_path.split('/')[-1].split('.')[0]
    body, start, end = extract_info(json_path)
    df.loc[df['source_video_id'] == int(transcription_id), 'body'] = body
    df.loc[df['source_video_id'] == int(transcription_id), 'start'] = start
    df.loc[df['source_video_id'] == int(transcription_id), 'end'] = end

# Apply the function to create new columns for first and last words
df['first_words'], df['last_words'] = zip(*df.apply(extract_first_last_words, axis=1))

# Display the resulting dataframe
print(df.head())

print(df['body'])

print(df['start'])

print(df['end'])